kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "fireboom.fullname" . }}-cfgmap
data:
  {{- $privateKey := genPrivateKey "rsa" -}}
  {{- $ca := genCAWithKey "fbCert" 7300 $privateKey -}}
  {{- $cert := genSignedCert "fireboom" (list "10.0.0.1" "10.0.0.2") (list "bar.com" "bat.com") 7300 $ca }}
  YUDAI_DB_URL: {{ .Values.database.url | quote }}
  token_jwt_key.key: |
    {{- $privateKey | nindent 4 }}
  token_jwt_key.pem: |-
    {{- $ca.Cert | nindent 4 }}
  config.yaml:
    {{- toYaml .Values.config | nindent 4 }}
