apiVersion: v1
kind: Service
metadata:
  name: oidc
  labels:
    app: oidc
    version: v1
    app.kubernetes.io/name: {{- include "fireboom.name" . }}
    app.kubernetes.io/version: v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
    kubesphere.io/alias-name: {{- include "fireboom.name" . }}-oidc
    kubesphere.io/serviceType: statelessservice
    kubesphere.io/description: 统一身份认证服务
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9825
      targetPort: 9825
      protocol: TCP
      name: http-9825
  selector:
    app: oidc
    app.kubernetes.io/name: {{- include "fireboom.name" . }}
    app.kubernetes.io/version: v1
