apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fireboom.fullname" . }}-web
  labels:
    app: web
    version: v1
    app.kubernetes.io/name: {{- include "fireboom.name" . }}
    app.kubernetes.io/version: v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: web
      version: v1
      app.kubernetes.io/name: {{- include "fireboom.name" . }}
      app.kubernetes.io/version: v1
  template:
    metadata:
      # {{- with .Values.podAnnotations }}
      # annotations:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      labels:
        app: web
        version: v1
        app.kubernetes.io/name: {{- include "fireboom.name" . }}
        app.kubernetes.io/version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
        kubesphere.io/imagepullsecrets: '{"container-4rxjqv":"harbor-211-101"}'
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: default
      serviceAccountName: default
      restartPolicy: Always
      securityContext: {}
      containers:
        - name: {{- include "fireboom.name" . }}-web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag | default latest }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy | default Always }}
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          env:
            - name: FB_API_URL
              value: 'fb-server:9991'
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
