apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    version: v1
    app.kubernetes.io/name: {{- include "fireboom.name" . }}
    app.kubernetes.io/version: v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
    kubesphere.io/alias-name: {{- include "fireboom.name" . }}-front
    kubesphere.io/serviceType: statelessservice
    kubesphere.io/description: 前端服务
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-80
  selector:
    app: web
    app.kubernetes.io/name: {{- include "fireboom.name" . }}
    app.kubernetes.io/version: v1
