apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireboom.fullname" . }}
  labels:
    {{- include "fireboom.labels" . | nindent 4 }}
  annotations:
    {{- include "fireboom.annotations" . | nindent 4 }}
    kubesphere.io/serviceType: statelessservice
    kubesphere.io/description: Fireboom server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9123
      targetPort: 9123
      protocol: TCP
      name: http-9123
      {{- if .Values.service.fbPort }}
      nodePort: {{ .Values.service.fbPort }}
      {{- end }}
    - port: 9991
      targetPort: 9991
      protocol: TCP
      name: http-9991
  selector:
    {{- include "fireboom.selectorLabels" . | nindent 6 }}
