apiVersion: v2
name: fireboom
description: A Fireboom Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "0.1.1"
readme: README.md

dependencies:
  - name: web
    version: 0.1.1
    condition: web.enabled
    alias: web
  - name: oidc
    version: 0.1.1
    condition: oidc.enabled
    alias: oidc
  - name: fireboom
    version: 0.1.1
    alias: fireboom