apiVersion: v2
name: fireboom
description: A Fireboom Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: frontend
    version: 0.1.0
    condition: frontend.enabled
  - name: backend
    version: 0.1.0
    condition: backend.enabled
  - name: oidc
    version: 0.1.0
    condition: oidc.enabled