global:
  imagePullSecrets: []
  web:
    enabled: true
  oidc:
    enabled: true

web:
  # web project image
  image:
    repository: fireboomapi/amis-admin_front
    pullPolicy: IfNotPresent
    tag: latest

  service:
    type: NodePort

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: fireboom.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  servicemesh:
    enabled: false

fireboom:
  # Pod replica count
  replicaCount: 1

  image:
    data:
      # where to pull the fireboom app data
      repository: fireboomapi/amis-admin_fb-data
      tag: "latest"
      pullPolicy: IfNotPresent
    fireboom:
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v2.0.10"
    hook:
      repository: fireboomapi/amis-admin_fb-hook
      tag: "latest"
      pullPolicy: IfNotPresent
  
  customEnv:
    DB_ADMIN: "postgres://postgres:KKziaPBkybHWH729@10.233.47.102/oidc_amis-admin"
    SUPER_ROLE_CODE: "admin"
    AppID: "set-your-own-tencent-oss-app-id"
    AppSecret: "set-your-own-tencent-oss-app-secret"

  service:
    type: ClusterIP
    externalUrl: 'http://192.168.211.213:30987'

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: fireboom.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  customInitContainers:
    - name: update-db
      image: 'fireboomapi/jq:alpine-3.19'
      command:
        - sh
        - '-c'
      args:
        - |
          jq '.kind = 3' /app/store/datasource/admin.json > temp.json
          mv temp.json /app/store/datasource/admin.json
      ports:
        - name: http-0
          containerPort: 1
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: share-app
          mountPath: /app
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent

  resources:
    fireboom: {}
    hook: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  servicemesh:
    enabled: true

oidc:
  # Pod replica count
  replicaCount: 1

  # Database of oidc
  database: 
    url: 'postgres://postgres:KKziaPBkybHWH729@10.233.47.102:5432/oidc_amis-admin?sslmode=disable'

  image:
    repository: fireboomapi/yudai
    pullPolicy: IfNotPresent
    tag: master

  service:
    type: ClusterIP

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  resources: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  servicemesh:
    enabled: false