
global:
  nameOverride: amis-admin
  fullnameOverride: amis-admin-test
  # global docker image registry
  imageRegistry: docker.io
  imagePullSecrets: []

web:
  enabled: true

backend:
  enabled: false 

oidc:
  enabled: true