apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fireboom.fullname" . }}
  labels:
    {{- include "fireboom.labels" . | nindent 4 }}
  annotations:
    {{- include "fireboom.annotations" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fireboom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.servicemesh.enabled }}
        sidecar.istio.io/inject: 'true'
        {{- end }}
      labels:
        {{- include "fireboom.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "fireboom.templateSpec" . | nindent 6 }}
      containers:
        - name: {{ include "fireboom.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          env:
            - name: FB_API_URL
              value: '{{ printf "%s-%s" .Release.Name "fireboom" | trunc 63 | trimSuffix "-" }}:9991'
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            timeoutSeconds: 3
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
